plugins {
    id 'com.android.application'
}

android {
    namespace 'com.homayoun.mousebuttontoggle'
    compileSdk 35

    defaultConfig {
        applicationId 'com.homayoun.mousebuttontoggle'
        minSdk 29
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    signingConfigs {
        debug {
            storeFile file(System.getProperty('user.home') + '/.android/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
    }

    buildFeatures {
        aidl true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
