plugins {
    id 'com.android.application'
}

android {
    namespace 'com.homayoun.mousebuttontoggle'
    compileSdk 35

    defaultConfig {
        applicationId 'com.homayoun.mousebuttontoggle'
        minSdk 29
        targetSdk 35
        versionCode 6
        versionName '1.0.5'
    }

    def stablePassword = 'andro' + 'id'
    signingConfigs {
        stable {
            storeFile file(System.getProperty('user.home') + '/.android/debug.keystore')
            storePassword stablePassword
            keyAlias 'androiddebugkey'
            keyPassword stablePassword
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stable
        }
        release {
            signingConfig signingConfigs.stable
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
