from pathlib import Path

p = Path('app/src/main/java/com/najme/perplexityprobe/PersianKeyboardService.java')
s = p.read_text()

def replace_once(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f'v1.8 patch: missing pattern: {label}')
    s = s.replace(old, new, 1)

# ---- Carry forward the validated v1.7 interaction changes ----
replace_once('import android.view.KeyEvent;\n', 'import android.view.KeyEvent;\nimport android.view.MotionEvent;\n', 'MotionEvent import')

replace_once('''    private int pendingBytes;\n    private int credentialAttempt;\n''', '''    private int pendingBytes;\n\n    private boolean backspaceHeld;\n    private boolean backspaceWordMode;\n    private final Runnable backspaceRepeater = new Runnable() {\n        @Override public void run() {\n            if (!backspaceHeld) return;\n            if (backspaceWordMode) {\n                deletePreviousWord();\n                main.postDelayed(this, 145L);\n                return;\n            }\n            InputConnection ic = getCurrentInputConnection();\n            CharSequence before = null;\n            try { if (ic != null) before = ic.getTextBeforeCursor(1, 0); } catch (Exception ignored) {}\n            if (before != null && before.length() > 0 && Character.isWhitespace(before.charAt(before.length() - 1))) {\n                backspaceWordMode = true;\n                main.postDelayed(this, 145L);\n            } else {\n                backspaceOnce();\n                main.postDelayed(this, 52L);\n            }\n        }\n    };\n\n    private int credentialAttempt;\n''', 'backspace state')

replace_once('''        bar.addView(toolbarButton("G⇄", v -> setStatus("Translate: next build")), toolbarLp(0.85f));\n        Button clip = toolbarButton("▣", v -> pasteClipboard());\n''', '''        bar.addView(toolbarButton("G⇄", v -> { stopVoiceForManualInput(); setStatus("Translate: next build"); }), toolbarLp(0.85f));\n        Button clip = toolbarButton("▣", v -> { stopVoiceForManualInput(); pasteClipboard(); });\n''', 'toolbar translate/clipboard stop')
replace_once('''        Button floating = toolbarButton("▱", v -> setStatus("Floating mode: next build"));\n''', '''        Button floating = toolbarButton("▱", v -> { stopVoiceForManualInput(); setStatus("Floating mode: next build"); });\n''', 'toolbar floating stop')

s = s.replace('actionKey("⌫", v -> backspace())', 'backspaceKey()')
if 'v -> backspace()' in s:
    raise SystemExit('v1.8 patch: old backspace action remains')

replace_once('''    private Button charKey(String label) {\n        Button b=baseKey(label,false); b.setOnClickListener(v -> commitText(label));\n        String[] vars=longPress.get(label); if (vars!=null) b.setOnLongClickListener(v -> { showVariants(b,vars); return true; });\n        return b;\n    }\n\n    private Button actionKey(String label, View.OnClickListener listener) { Button b=baseKey(label,true); b.setOnClickListener(listener); return b; }\n''', '''    private Button charKey(String label) {\n        Button b=baseKey(label,false);\n        b.setOnClickListener(v -> { stopVoiceForManualInput(); commitText(label); });\n        String[] vars=longPress.get(label);\n        if (vars!=null) b.setOnLongClickListener(v -> { stopVoiceForManualInput(); showVariants(b,vars); return true; });\n        return b;\n    }\n\n    private Button actionKey(String label, View.OnClickListener listener) {\n        Button b=baseKey(label,true);\n        b.setOnClickListener(v -> { stopVoiceForManualInput(); listener.onClick(v); });\n        return b;\n    }\n\n    private Button backspaceKey() {\n        Button b=baseKey("⌫",true);\n        b.setOnTouchListener((v,event) -> {\n            int action=event.getActionMasked();\n            if(action==MotionEvent.ACTION_DOWN){\n                stopVoiceForManualInput();\n                backspaceHeld=true; backspaceWordMode=false;\n                backspaceOnce();\n                main.removeCallbacks(backspaceRepeater);\n                main.postDelayed(backspaceRepeater,330L);\n                return true;\n            }\n            if(action==MotionEvent.ACTION_UP||action==MotionEvent.ACTION_CANCEL){\n                backspaceHeld=false;\n                main.removeCallbacks(backspaceRepeater);\n                return true;\n            }\n            return true;\n        });\n        return b;\n    }\n''', 'key wrappers')

replace_once('''    private String alphaLabel(){return persian?"ابپ":"ABC";}\n    private void toggleLanguage(){\n        if(running){setStatus("Stop voice before changing language");return;}\n        persian=!persian; shift=false; layer=Layer.ALPHA; getSharedPreferences("keyboard",MODE_PRIVATE).edit().putBoolean("persian",persian).apply(); render(); setStatus(readyText());\n    }\n''', '''    private String alphaLabel(){return persian?"ابپ":"ABC";}\n    private void toggleLanguage(){\n        stopVoiceForManualInput();\n        persian=!persian; shift=false; layer=Layer.ALPHA; getSharedPreferences("keyboard",MODE_PRIVATE).edit().putBoolean("persian",persian).apply(); render(); setStatus(readyText());\n    }\n''', 'language switch')

replace_once('''    private void backspace(){\n        InputConnection ic=getCurrentInputConnection(); if(ic==null)return; try{CharSequence sel=ic.getSelectedText(0); if(sel!=null&&sel.length()>0)ic.commitText("",1); else ic.deleteSurroundingText(1,0);}catch(Exception ignored){}\n    }\n''', '''    private void backspaceOnce(){\n        InputConnection ic=getCurrentInputConnection(); if(ic==null)return;\n        try{CharSequence sel=ic.getSelectedText(0); if(sel!=null&&sel.length()>0)ic.commitText("",1); else ic.deleteSurroundingText(1,0);}catch(Exception ignored){}\n    }\n\n    private void deletePreviousWord(){\n        InputConnection ic=getCurrentInputConnection(); if(ic==null)return;\n        try{\n            CharSequence sel=ic.getSelectedText(0);\n            if(sel!=null&&sel.length()>0){ic.commitText("",1);return;}\n            CharSequence seq=ic.getTextBeforeCursor(256,0);\n            if(seq==null||seq.length()==0)return;\n            String before=seq.toString();\n            int end=before.length();\n            while(end>0&&Character.isWhitespace(before.charAt(end-1)))end--;\n            int start=end;\n            while(start>0&&!Character.isWhitespace(before.charAt(start-1)))start--;\n            int count=before.length()-start;\n            if(count<=0)count=1;\n            ic.deleteSurroundingText(count,0);\n        }catch(Exception ignored){}\n    }\n''', 'backspace implementation')

replace_once('''    private void switchToGboard(){\n        if(running)abortForEditorChange(); InputMethodManager imm=(InputMethodManager)getSystemService(INPUT_METHOD_SERVICE); String id=null;\n''', '''    private void stopVoiceForManualInput(){\n        if(!running)return;\n        running=false; completed=true; stopRequested=true; awaitingCredential=false; retryAfterPageLoad=false;\n        backspaceHeld=false; main.removeCallbacks(backspaceRepeater);\n        stopAudioRecord(); clearPending();\n        WebSocket ws=webSocket; webSocket=null; if(ws!=null)ws.cancel();\n        InputConnection old=boundConnection; boundConnection=null;\n        if(old!=null)try{old.finishComposingText();}catch(Exception ignored){}\n        synchronized(expectedSelectionUpdates){expectedSelectionUpdates.clear();}\n        hasComposingTail=false;\n        setCollapsed(false); updateMicUi(); setStatus(readyText());\n    }\n\n    private void switchToGboard(){\n        stopVoiceForManualInput(); InputMethodManager imm=(InputMethodManager)getSystemService(INPUT_METHOD_SERVICE); String id=null;\n''', 'manual voice interruption')

replace_once('''    @Override public void onDestroy(){running=false;stopRequested=true;stopAudioRecord();clearPending();if(webSocket!=null)webSocket.cancel();if(auth!=null){auth.removeJavascriptInterface("AndroidKeyboard");auth.destroy();}http.dispatcher().executorService().shutdown();super.onDestroy();}\n''', '''    @Override public void onDestroy(){running=false;stopRequested=true;backspaceHeld=false;main.removeCallbacks(backspaceRepeater);stopAudioRecord();clearPending();if(webSocket!=null)webSocket.cancel();if(auth!=null){auth.removeJavascriptInterface("AndroidKeyboard");auth.destroy();}http.dispatcher().executorService().shutdown();super.onDestroy();}\n''', 'onDestroy cleanup')

# ---- v1.8: manual-duration dictation, immutable committed text, external-caret cancellation ----
replace_once('''    private static final long MAX_CAPTURE_MS = 60000L;\n''', '', 'remove automatic 60 second capture limit')

replace_once('''    private final ArrayDeque<byte[]> pendingAudio = new ArrayDeque<>();\n    private final Map<String, String[]> longPress = new HashMap<>();\n''', '''    private final ArrayDeque<byte[]> pendingAudio = new ArrayDeque<>();\n    private final ArrayDeque<Long> expectedSelectionUpdates = new ArrayDeque<>();\n    private final Map<String, String[]> longPress = new HashMap<>();\n''', 'selection expectation queue')

replace_once('''    private String partialTranscript = "";\n    private int pendingBytes;\n''', '''    private String partialTranscript = "";\n    private int committedFinalChars;\n    private boolean hasComposingTail;\n    private int pendingBytes;\n''', 'stable transcript fields')

replace_once('''    @Override public void onFinishInput() {\n        inputGeneration++;\n        if (running) abortForEditorChange();\n        editorInfo = null;\n        super.onFinishInput();\n    }\n\n    private void render() {\n''', '''    @Override public void onFinishInput() {\n        inputGeneration++;\n        if (running) abortForEditorChange();\n        editorInfo = null;\n        super.onFinishInput();\n    }\n\n    @Override public void onUpdateSelection(int oldSelStart, int oldSelEnd, int newSelStart, int newSelEnd, int candidatesStart, int candidatesEnd) {\n        super.onUpdateSelection(oldSelStart, oldSelEnd, newSelStart, newSelEnd, candidatesStart, candidatesEnd);\n        if(!running)return;\n        if(oldSelStart==newSelStart&&oldSelEnd==newSelEnd)return;\n        if(consumeExpectedSelection(newSelStart,newSelEnd))return;\n        boolean withinComposing=candidatesStart>=0&&candidatesEnd>=candidatesStart\n                &&newSelStart>=candidatesStart&&newSelStart<=candidatesEnd\n                &&newSelEnd>=candidatesStart&&newSelEnd<=candidatesEnd;\n        if(withinComposing)return;\n        stopVoiceForManualInput();\n    }\n\n    private long selectionKey(int start,int end){return(((long)start)<<32)^(end&0xffffffffL);}\n    private void rememberProgrammaticSelection(){\n        InputConnection ic=boundConnection;if(ic==null)return;\n        try{\n            android.view.inputmethod.ExtractedTextRequest req=new android.view.inputmethod.ExtractedTextRequest();\n            android.view.inputmethod.ExtractedText et=ic.getExtractedText(req,0);\n            if(et==null)return;\n            long key=selectionKey(et.selectionStart,et.selectionEnd);\n            synchronized(expectedSelectionUpdates){\n                while(expectedSelectionUpdates.size()>=10)expectedSelectionUpdates.removeFirst();\n                expectedSelectionUpdates.addLast(key);\n            }\n        }catch(Exception ignored){}\n    }\n    private boolean consumeExpectedSelection(int start,int end){\n        long key=selectionKey(start,end);\n        synchronized(expectedSelectionUpdates){return expectedSelectionUpdates.removeFirstOccurrence(key);}\n    }\n\n    private void render() {\n''', 'outside keyboard caret cancellation')

replace_once('''        synchronized(textLock){finalTranscript.setLength(0);finalTokenIds.clear();partialTranscript="";}\n        resetAudio(); running=true; stopRequested=false; completed=false; awaitingCredential=true; credentialAttempt=0; retryAfterPageLoad=false; lastCredentialError=""; updateMicUi();\n''', '''        synchronized(textLock){finalTranscript.setLength(0);finalTokenIds.clear();partialTranscript="";committedFinalChars=0;hasComposingTail=false;}\n        synchronized(expectedSelectionUpdates){expectedSelectionUpdates.clear();}\n        resetAudio(); running=true; stopRequested=false; completed=false; awaitingCredential=true; credentialAttempt=0; retryAfterPageLoad=false; lastCredentialError=""; updateMicUi();\n''', 'reset stable transcript state')

replace_once('''        JSONObject c=new JSONObject();put(c,"api_key",apiKey);put(c,"model","stt-rt-v4");put(c,"audio_format","pcm_s16le");put(c,"sample_rate",SAMPLE_RATE);put(c,"num_channels",1);put(c,"enable_endpoint_detection",true);put(c,"max_endpoint_delay_ms",2000);JSONArray h=new JSONArray();h.put(persian?"fa":"en");put(c,"language_hints",h);\n''', '''        JSONObject c=new JSONObject();put(c,"api_key",apiKey);put(c,"model","stt-rt-v4");put(c,"audio_format","pcm_s16le");put(c,"sample_rate",SAMPLE_RATE);put(c,"num_channels",1);put(c,"enable_endpoint_detection",false);JSONArray h=new JSONArray();h.put(persian?"fa":"en");put(c,"language_hints",h);put(c,"language_hints_strict",true);\n''', 'manual endpointing and strict language')

replace_once('''                if(audioRecord.getState()!=AudioRecord.STATE_INITIALIZED)throw new IllegalStateException("AudioRecord not initialized");audioRecord.startRecording();byte[] buf=new byte[AUDIO_CHUNK];long deadline=System.currentTimeMillis()+MAX_CAPTURE_MS;\n                while(running&&!stopRequested&&System.currentTimeMillis()<deadline){int n;try{n=audioRecord.read(buf,0,buf.length);}catch(Exception e){if(stopRequested||!running)break;throw e;}if(n>0){byte[] chunk=Arrays.copyOf(buf,n);if(!bufferOrSend(chunk))throw new IllegalStateException("Audio send rejected");}else if(n<0&&!stopRequested)throw new IllegalStateException("Audio read failed");}\n                if(running&&!stopRequested&&System.currentTimeMillis()>=deadline){stopRequested=true;main.post(()->setStatus(persian?"در حال نهایی‌سازی…":"Finalizing…"));}\n                stopAudioRecord();synchronized(audioLock){audioDone=true;}if(running&&!completed)maybeFinish();\n''', '''                if(audioRecord.getState()!=AudioRecord.STATE_INITIALIZED)throw new IllegalStateException("AudioRecord not initialized");audioRecord.startRecording();byte[] buf=new byte[AUDIO_CHUNK];\n                while(running&&!stopRequested){int n;try{n=audioRecord.read(buf,0,buf.length);}catch(Exception e){if(stopRequested||!running)break;throw e;}if(n>0){byte[] chunk=Arrays.copyOf(buf,n);if(!bufferOrSend(chunk))throw new IllegalStateException("Audio send rejected");}else if(n<0&&!stopRequested)throw new IllegalStateException("Audio read failed");}\n                stopAudioRecord();synchronized(audioLock){audioDone=true;}if(running&&!completed)maybeFinish();\n''', 'remove timed audio stop')

replace_once('''    private void publish(boolean finish){\n        final String display;synchronized(textLock){display=finalTranscript.toString()+(finish?"":partialTranscript);}main.post(()->{if(!sessionStillBound()&&!finish)return;if(boundConnection==null||activeGeneration!=inputGeneration||getCurrentInputConnection()!=boundConnection){if(running)abortForEditorChange();return;}try{boundConnection.setComposingText(display,1);if(finish)boundConnection.finishComposingText();}catch(Exception e){abortForEditorChange();}});\n    }\n''', '''    private void publish(boolean finish){\n        main.post(()->{\n            if(!sessionStillBound()&&!finish)return;\n            if(boundConnection==null||activeGeneration!=inputGeneration||getCurrentInputConnection()!=boundConnection){if(running)abortForEditorChange();return;}\n            String newFinal;String partial;int targetFinalChars;\n            synchronized(textLock){\n                String allFinal=finalTranscript.toString();\n                int from=Math.min(committedFinalChars,allFinal.length());\n                newFinal=allFinal.substring(from);\n                partial=partialTranscript;\n                targetFinalChars=allFinal.length();\n            }\n            try{\n                if(!newFinal.isEmpty()){\n                    boundConnection.commitText(newFinal,1);\n                    rememberProgrammaticSelection();\n                    synchronized(textLock){if(committedFinalChars<targetFinalChars)committedFinalChars=targetFinalChars;}\n                    hasComposingTail=false;\n                }\n                if(!partial.isEmpty()){\n                    boundConnection.setComposingText(partial,1);\n                    hasComposingTail=true;\n                    rememberProgrammaticSelection();\n                }else if(hasComposingTail){\n                    boundConnection.setComposingText("",1);\n                    hasComposingTail=false;\n                    rememberProgrammaticSelection();\n                }\n                if(finish){\n                    boundConnection.finishComposingText();\n                    hasComposingTail=false;\n                    rememberProgrammaticSelection();\n                }\n            }catch(Exception e){abortForEditorChange();}\n        });\n    }\n''', 'commit final text incrementally')

replace_once('''    private void abortForEditorChange(){\n        InputConnection old=boundConnection;running=false;stopRequested=true;awaitingCredential=false;stopAudioRecord();clearPending();WebSocket ws=webSocket;webSocket=null;if(ws!=null)ws.cancel();if(old!=null)try{old.finishComposingText();}catch(Exception ignored){} boundConnection=null;\n        main.post(()->{setCollapsed(false);updateMicUi();setStatus("Voice cancelled — editor changed");});\n    }\n''', '''    private void abortForEditorChange(){\n        InputConnection old=boundConnection;running=false;stopRequested=true;awaitingCredential=false;stopAudioRecord();clearPending();WebSocket ws=webSocket;webSocket=null;if(ws!=null)ws.cancel();if(old!=null)try{old.finishComposingText();}catch(Exception ignored){} boundConnection=null;\n        hasComposingTail=false;synchronized(expectedSelectionUpdates){expectedSelectionUpdates.clear();}\n        main.post(()->{setCollapsed(false);updateMicUi();setStatus("Voice cancelled — editor changed");});\n    }\n''', 'editor abort stable cleanup')

# Sanity checks on the generated source before Gradle sees it.
if 'MAX_CAPTURE_MS' in s:
    raise SystemExit('v1.8 patch: timed capture limit still present')
if 'enable_endpoint_detection",true' in s:
    raise SystemExit('v1.8 patch: endpoint detection still enabled')
if 'setComposingText(display,1)' in s:
    raise SystemExit('v1.8 patch: whole-session composing still present')
if 'language_hints_strict",true' not in s:
    raise SystemExit('v1.8 patch: strict language hint missing')

p.write_text(s)
print('Applied Persian keyboard v1.8 persistent/stable dictation patch')
