plugins {
    id 'com.android.application'
}

android {
    namespace 'com.najme.perplexityprobe'
    compileSdk 35

    signingConfigs {
        debug {
            storeFile file(System.getProperty('user.home') + '/.android/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    defaultConfig {
        applicationId 'com.najme.perplexityprobe'
        minSdk 26
        targetSdk 35
        versionCode 19
        versionName '1.9'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
