#!/usr/bin/env python3
from pathlib import Path
import runpy,re
ROOT=Path('runtime_probes/chatgpt-webview-stable-probe'); PKG=ROOT/'app/src/main/java/com/homayounisaghar/chatgptwebviewprobe'
# Reuse the already-qualified v74 DOM read/composer/send primitives, then regenerate v93 as the base.
runpy.run_path('ci/generate_chatgpt_webview_v74_planner_format_repair.py',run_name='__main__')
v74=(PKG/'OrchestratorPlannerCoreV74Activity.java').read_text()
a=v74.index('    private String readJs(){'); b=v74.index('    private void eval(',a)
prims=v74[a:b].replace('private String readJs()','private String plannerReadJs()',1).replace('private String setDraftJs(String text)','private String plannerSetDraftJs(String text)',1).replace('private String sendJs(String expectedHash)','private String plannerSendJs(String expectedHash)',1)
runpy.run_path('ci/generate_chatgpt_webview_v93_dashboard_telemetry_budget_repair.py',run_name='__main__')
s=(PKG/'OrchestratorDashboardV93Activity.java').read_text()
s=s.replace('public class OrchestratorDashboardV93Activity extends Activity {','public class OrchestratorDashboardV94PlannerIngressActivity extends Activity {',1)
s=s.replace('cp-v93-dashboard-telemetry-budget-repair-v1','cp-v94-dashboard-stateless-planner-recipe-only-v1',1).replace('dashboard-multichat-read-plane-telemetry-budget-repair','dashboard-stateless-planner-recipe-only',1).replace('private final String testId="cp892-"+UUID.randomUUID();','''private final String testId="cp900-"+UUID.randomUUID();
    private static final int MAX_PLANNER_POLLS=240,MAX_PLANNER_COMMAND_CHARS=12000; private static final long PLANNER_POLL_MS=500L;
    private EditText plannerInput; private TextView plannerResult; private Button plannerButton; private SharedPreferences plannerJournal;
    private boolean plannerRunning=false; private long plannerGeneration=0L; private int plannerPolls=0,plannerChatEffectDispatches=0,targetChatEffectDispatches=0;
    private String plannerPhase="IDLE",plannerRequestId="",plannerRequestDigest="",plannerExpectedComposerHash="-",plannerBaselineAssistantHash="-",plannerPacket="",plannerParseError="";''',1).replace('TelemetryConfigV93','TelemetryConfigV94')
s=s.replace('navJournal=getSharedPreferences("cp_v91_dashboard_navigation",MODE_PRIVATE);','navJournal=getSharedPreferences("cp_v91_dashboard_navigation",MODE_PRIVATE); plannerJournal=getSharedPreferences("cp_v94_stateless_planner",MODE_PRIVATE);',1)
old='''        Button dash=new Button(this);dash.setText("DASHBOARD");dash.setOnClickListener(v->showDashboard("Dashboard"));
        Button chat=new Button(this);chat.setText("CHAT");chat.setOnClickListener(v->showChat("Chat"));
        bindButton=new Button(this);bindButton.setText("BIND CURRENT");bindButton.setOnClickListener(v->bindCurrent());
        Button refresh=new Button(this);refresh.setText("REFRESH ALL");refresh.setOnClickListener(v->{if(scheduler!=null)scheduler.refreshAll();});'''
new='''        Button dash=new Button(this);dash.setText("DASHBOARD");dash.setOnClickListener(v->{if(!plannerRunning)showDashboard("Dashboard");});
        Button chat=new Button(this);chat.setText("CHAT");chat.setOnClickListener(v->{if(plannerRunning){status.setText("Planner active; navigation fenced.");return;}showChat("Chat");});
        bindButton=new Button(this);bindButton.setText("BIND CURRENT");bindButton.setOnClickListener(v->bindCurrent());
        Button refresh=new Button(this);refresh.setText("REFRESH ALL");refresh.setOnClickListener(v->{if(plannerRunning){status.setText("Planner active; refresh fenced.");return;}if(scheduler!=null)scheduler.refreshAll();});'''; assert old in s; s=s.replace(old,new,1)
old='''        aliasInput=new EditText(this);aliasInput.setSingleLine(true);aliasInput.setHint("Local alias for Bind current (optional)");
        root.addView(aliasInput,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(46)));
        header=new TextView(this);header.setTextSize(13f);header.setPadding(dp(8),dp(5),dp(8),dp(5));'''
new='''        aliasInput=new EditText(this);aliasInput.setSingleLine(true);aliasInput.setHint("Local alias for Bind current (optional)"); root.addView(aliasInput,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(46)));
        plannerInput=new EditText(this);plannerInput.setHint("Command to fresh Planner chat"); root.addView(plannerInput,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(58)));
        LinearLayout pr=new LinearLayout(this);pr.setOrientation(LinearLayout.HORIZONTAL);plannerButton=new Button(this);plannerButton.setText("RUN PLANNER");plannerButton.setOnClickListener(v->startPlannerRequest());Button pc=new Button(this);pc.setText("CLEAR");pc.setOnClickListener(v->{if(!plannerRunning){plannerInput.setText("");plannerResult.setText("No Planner recipe yet.");}});pr.addView(plannerButton,new LinearLayout.LayoutParams(0,dp(42),1.4f));pr.addView(pc,new LinearLayout.LayoutParams(0,dp(42),.8f));root.addView(pr,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(42)));
        plannerResult=new TextView(this);plannerResult.setTextSize(11f);plannerResult.setPadding(dp(8),dp(4),dp(8),dp(4));plannerResult.setText("No Planner recipe yet.");root.addView(plannerResult,new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(112)));
        header=new TextView(this);header.setTextSize(13f);header.setPadding(dp(8),dp(5),dp(8),dp(5));'''; assert old in s; s=s.replace(old,new,1)
s=s.replace('''                if(pendingOpenPath!=null)h.postDelayed(()->verifyOpenReceipt(),350L);''','''                if(plannerRunning){long g=plannerGeneration;h.postDelayed(()->plannerObserve(g),350L);return;} if(pendingOpenPath!=null)h.postDelayed(()->verifyOpenReceipt(),350L);''',1)
old='''    private void showDashboard(String msg){
        chatMode=false;foreground.setVisibility(View.GONE);dashboardScroll.setVisibility(View.VISIBLE);
        aliasInput.setVisibility(View.GONE);bindButton.setEnabled(false);renderDashboard();status.setText(msg);
    }

    private void showChat(String msg){
        chatMode=true;dashboardScroll.setVisibility(View.GONE);foreground.setVisibility(View.VISIBLE);
        aliasInput.setVisibility(View.VISIBLE);bindButton.setEnabled(true);status.setText(msg);
    }'''
new='''    private void showDashboard(String msg){chatMode=false;foreground.setAlpha(1f);foreground.setVisibility(View.GONE);dashboardScroll.setVisibility(View.VISIBLE);aliasInput.setVisibility(View.GONE);plannerInput.setVisibility(View.VISIBLE);plannerButton.setVisibility(View.VISIBLE);plannerResult.setVisibility(View.VISIBLE);bindButton.setEnabled(false);foreground.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,1f));renderDashboard();status.setText(msg);}
    private void showChat(String msg){if(plannerRunning){status.setText("Planner active; Chat mode fenced.");return;}chatMode=true;dashboardScroll.setVisibility(View.GONE);foreground.setAlpha(1f);foreground.setVisibility(View.VISIBLE);foreground.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,0,1f));aliasInput.setVisibility(View.VISIBLE);plannerInput.setVisibility(View.GONE);plannerButton.setVisibility(View.GONE);plannerResult.setVisibility(View.GONE);bindButton.setEnabled(true);status.setText(msg);}
    private void showPlannerSurface(String msg){chatMode=false;dashboardScroll.setVisibility(View.VISIBLE);aliasInput.setVisibility(View.GONE);bindButton.setEnabled(false);plannerInput.setVisibility(View.VISIBLE);plannerButton.setVisibility(View.VISIBLE);plannerResult.setVisibility(View.VISIBLE);foreground.setAlpha(0f);foreground.setVisibility(View.VISIBLE);foreground.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(1)));renderDashboard();status.setText(msg);}'''; assert old in s; s=s.replace(old,new,1)
s=s.replace('''    private void openBinding(ConversationBindingV91 bnd){
        if(bnd==null''','''    private void openBinding(ConversationBindingV91 bnd){
        if(plannerRunning){status.setText("Open fenced while Planner is active.");return;} if(bnd==null''',1)
planner=r'''
    private void startPlannerRequest(){if(plannerRunning)return;if(scheduler!=null&&scheduler.scanning){status.setText("Finish Refresh all first.");return;}String c=plannerInput.getText().toString().trim();if(c.isEmpty()||c.length()>MAX_PLANNER_COMMAND_CHARS){status.setText("Enter a bounded Planner command.");return;}plannerRequestId="req-"+UUID.randomUUID();plannerRequestDigest=sha256(c);plannerPacket=buildPlannerPacket(c);plannerGeneration++;plannerPolls=0;plannerRunning=true;plannerPhase="WAIT_FRESH_HOME";plannerExpectedComposerHash="-";plannerBaselineAssistantHash="-";plannerButton.setEnabled(false);plannerResult.setText("Planner: opening fresh chat...");boolean ok=plannerJournal.edit().putString("request_id",plannerRequestId).putString("request_digest",plannerRequestDigest).putString("status","CLAIMED_BEFORE_FRESH_PLANNER_NAV").commit();if(!ok){plannerFail("PLANNER_NAV_CLAIM_FAILED");return;}emit("PLANNER_REQUEST_STARTED",null,"UNKNOWN",jsonExtra("request_digest",plannerRequestDigest,"planner_phase",plannerPhase));showPlannerSurface("Planner transaction active. Target effects disabled.");foreground.loadUrl("https://chatgpt.com/");}
    private String buildPlannerPacket(String c){StringBuilder refs=new StringBuilder();for(int i=0;i<registry.bindings.size();i++){ConversationBindingV91 b=registry.bindings.get(i);refs.append("- CHAT_").append(i+1).append(" | alias=").append(JSONObject.quote(b.alias)).append("\n");}return "[CF_PLANNER_REQUEST v1]\nrequest_id="+plannerRequestId+"\nrequest_digest="+plannerRequestDigest+"\nauthority=CANDIDATE_ONLY\nmode=RECIPE_ONLY\nresponse_schema=cf-planner-recipe.v1\nobserved_state_digest=NONE\n\nYou are the semantic Planner. The Android app has no semantic intelligence. Interpret the user's intent and return exactly one JSON object, no prose or code fence. Required keys: protocol, request_id, request_digest, observed_state_digest, status, operations, ambiguities. protocol must be cf-planner-recipe.v1 and correlation fields must exactly echo this request. status is READY, NEEDS_CLARIFICATION, NO_ACTION, or UNSUPPORTED. Allowed capabilities: chat.refresh_state, chat.send_message, chat.send_attachment. Use only the chat refs listed below. READY operations use {op_id,capability,target:{chat_ref},arguments}. Non-READY returns operations=[].\nAVAILABLE_CHAT_REFS:\n"+refs+"\nUSER_INSTRUCTION_BEGIN\n"+c+"\nUSER_INSTRUCTION_END\n[END_CF_PLANNER_REQUEST]";}
    private void plannerObserve(long g){if(!plannerRunning||g!=plannerGeneration)return;if(++plannerPolls>MAX_PLANNER_POLLS){plannerFail("PLANNER_OBSERVATION_BUDGET_EXHAUSTED");return;}eval(foreground,plannerReadJs(),o->{if(!plannerRunning||g!=plannerGeneration)return;if(!o.optBoolean("success",false)){plannerLater(g);return;}String path=o.optString("local_path","");if("WAIT_FRESH_HOME".equals(plannerPhase)){boolean fresh="complete".equals(o.optString("ready",""))&&"/".equals(path)&&o.optInt("turn_count",-1)==0&&o.optInt("composer_candidate_count",0)==1&&o.optInt("stop_candidate_count",0)==0;if(!fresh){plannerLater(g);return;}plannerBaselineAssistantHash=o.optString("last_assistant_hash","-");plannerWrite(g);return;}if("WAIT_COMPOSER_RECEIPT".equals(plannerPhase)){if(!"/".equals(path)||o.optInt("composer_candidate_count",0)!=1||o.optInt("send_candidate_count",0)!=1||!plannerExpectedComposerHash.equals(o.optString("composer_hash","-"))){plannerLater(g);return;}plannerSend(g);return;}if("WAIT_SEND_RECEIPT".equals(plannerPhase)){if(!plannerExpectedComposerHash.equals(o.optString("last_user_hash","-"))||!path.matches("^/c/[^/?#]+$")){plannerLater(g);return;}plannerJournal.edit().putString("status","PLANNER_SEND_RECEIPT_CONFIRMED").commit();plannerPhase="WAIT_RESPONSE";emit("PLANNER_SEND_RECEIPT",null,"UNKNOWN",jsonExtra("request_digest",plannerRequestDigest,"planner_route_hash",sha256(path)));plannerLater(g);return;}if("WAIT_RESPONSE".equals(plannerPhase)){boolean ready=plannerExpectedComposerHash.equals(o.optString("last_user_hash","-"))&&!"-".equals(o.optString("last_assistant_hash","-"))&&!o.optString("last_assistant_hash","-").equals(plannerBaselineAssistantHash)&&o.optInt("stop_candidate_count",0)==0&&o.optInt("assistant_completion_candidate_count",0)>=1;if(!ready){plannerLater(g);return;}plannerRecipe(o.optString("last_assistant_text",""));return;}plannerFail("PLANNER_UNKNOWN_PHASE");});}
    private void plannerLater(long g){if(plannerRunning&&g==plannerGeneration)h.postDelayed(()->plannerObserve(g),PLANNER_POLL_MS);}
    private void plannerWrite(long g){if(!plannerJournal.edit().putString("status","CLAIMED_BEFORE_PLANNER_COMPOSER_WRITE").commit()){plannerFail("PLANNER_COMPOSER_CLAIM_FAILED");return;}eval(foreground,plannerSetDraftJs(plannerPacket),o->{if(!plannerRunning||g!=plannerGeneration)return;if(!o.optBoolean("success",false)||!o.optBoolean("mutated",false)||o.optInt("composer_count",0)!=1){plannerFail("PLANNER_COMPOSER_WRITE_UNCERTAIN_NO_REPLAY");return;}plannerExpectedComposerHash=o.optString("composer_hash","-");if("-".equals(plannerExpectedComposerHash)){plannerFail("PLANNER_COMPOSER_HASH_MISSING");return;}plannerPhase="WAIT_COMPOSER_RECEIPT";emit("PLANNER_COMPOSER_WRITE",null,"UNKNOWN",jsonExtra("request_digest",plannerRequestDigest,"composer_hash",plannerExpectedComposerHash));plannerLater(g);});}
    private void plannerSend(long g){if(!plannerJournal.edit().putString("status","CLAIMED_BEFORE_PLANNER_SEND").putString("composer_hash",plannerExpectedComposerHash).commit()){plannerFail("PLANNER_SEND_CLAIM_FAILED");return;}eval(foreground,plannerSendJs(plannerExpectedComposerHash),o->{if(!plannerRunning||g!=plannerGeneration)return;boolean ok=o.optBoolean("success",false)&&o.optBoolean("dispatched",false)&&o.optBoolean("click_observed",false)&&o.optInt("send_match_count",0)==1&&plannerExpectedComposerHash.equals(o.optString("composer_hash","-"));if(!ok){plannerFail("PLANNER_SEND_UNCERTAIN_NO_REPLAY");return;}plannerChatEffectDispatches++;plannerPhase="WAIT_SEND_RECEIPT";emit("PLANNER_SEND_DISPATCH",null,"UNKNOWN",jsonExtra("request_digest",plannerRequestDigest,"planner_chat_effect_dispatches",plannerChatEffectDispatches,"target_chat_effect_dispatches",targetChatEffectDispatches));plannerLater(g);});}
    private void plannerRecipe(String raw){JSONObject r=parsePlannerRecipe(raw);if(r==null){plannerResult.setText("Planner reply rejected mechanically: "+plannerParseError);plannerFail("PLANNER_RECIPE_PARSE_REJECTED");return;}String st=r.optString("status","");int n=r.optJSONArray("operations").length();plannerJournal.edit().putString("status","RECIPE_ACCEPTED_LOCAL_ONLY").commit();plannerRunning=false;plannerPhase="RECIPE_READY";plannerButton.setEnabled(true);emit("PLANNER_RECIPE_ACCEPTED",null,st,jsonExtra("request_digest",plannerRequestDigest,"recipe_status",st,"operation_count",n,"target_chat_effect_dispatches",targetChatEffectDispatches));try{plannerResult.setText("Recipe "+st+" (local only; not executed)\n"+r.toString(2));}catch(Exception e){plannerResult.setText("Recipe "+st+" accepted locally.");}showDashboard("Planner recipe received. Target effects remain disabled.");}
    private JSONObject parsePlannerRecipe(String raw){plannerParseError="";try{String x=raw==null?"":raw.trim();if(x.length()<2||x.charAt(0)!='{'||x.charAt(x.length()-1)!='}'){plannerParseError="not exactly one JSON object";return null;}JSONTokener t=new JSONTokener(x);Object z=t.nextValue();if(!(z instanceof JSONObject)||t.nextClean()!=0){plannerParseError="extra prose or multiple JSON values";return null;}JSONObject o=(JSONObject)z;if(!keys(o,"protocol","request_id","request_digest","observed_state_digest","status","operations","ambiguities")||!"cf-planner-recipe.v1".equals(o.optString("protocol",""))||!plannerRequestId.equals(o.optString("request_id",""))||!plannerRequestDigest.equals(o.optString("request_digest",""))||!"NONE".equals(o.optString("observed_state_digest",""))){plannerParseError="contract/correlation mismatch";return null;}String st=o.optString("status","");if(!one(st,"READY","NEEDS_CLARIFICATION","NO_ACTION","UNSUPPORTED")){plannerParseError="unknown status";return null;}JSONArray ops=o.optJSONArray("operations"),amb=o.optJSONArray("ambiguities");if(ops==null||amb==null||ops.length()>8||amb.length()>8||("READY".equals(st)?(ops.length()<1||amb.length()!=0):(ops.length()!=0))||("NEEDS_CLARIFICATION".equals(st)&&amb.length()<1)){plannerParseError="status/cardinality invalid";return null;}Set<String> ids=new HashSet<>();for(int i=0;i<ops.length();i++){JSONObject op=ops.optJSONObject(i);if(op==null||!keys(op,"op_id","capability","target","arguments")||!ids.add(op.optString("op_id",""))){plannerParseError="operation invalid";return null;}String cap=op.optString("capability","");if(!one(cap,"chat.refresh_state","chat.send_message","chat.send_attachment")){plannerParseError="unsupported capability";return null;}JSONObject tar=op.optJSONObject("target"),args=op.optJSONObject("arguments");if(tar==null||args==null||!keys(tar,"chat_ref")||!knownRef(tar.optString("chat_ref",""))){plannerParseError="target invalid";return null;}if("chat.refresh_state".equals(cap)){if(args.length()!=0)return failParse("refresh args invalid");}else if("chat.send_message".equals(cap)){if(!keys(args,"message_text")||args.optString("message_text","").isEmpty())return failParse("message args invalid");}else if(!(keys(args,"attachment_ref")||keys(args,"attachment_ref","message_text"))||args.optString("attachment_ref","").isEmpty())return failParse("attachment args invalid");}return o;}catch(Exception e){plannerParseError="JSON parse exception";return null;}}
    private JSONObject failParse(String x){plannerParseError=x;return null;} private boolean knownRef(String r){for(int i=0;i<registry.bindings.size();i++)if(("CHAT_"+(i+1)).equals(r))return true;return false;} private static boolean one(String x,String...v){for(String a:v)if(a.equals(x))return true;return false;} private static boolean keys(JSONObject o,String...v){Set<String>a=new HashSet<>();java.util.Iterator<String>it=o.keys();while(it.hasNext())a.add(it.next());Set<String>b=new HashSet<>();for(String x:v)b.add(x);return a.equals(b);}
    private void plannerFail(String why){if(plannerJournal!=null)plannerJournal.edit().putString("status",why).commit();plannerRunning=false;plannerPhase="FAILED";if(plannerButton!=null)plannerButton.setEnabled(true);emit("PLANNER_FAILED",null,"UNKNOWN",jsonExtra("request_digest",plannerRequestDigest,"reason",why,"planner_chat_effect_dispatches",plannerChatEffectDispatches,"target_chat_effect_dispatches",targetChatEffectDispatches));showDashboard("Planner stopped safely: "+why+". No target action executed.");}
'''
mark='    private static final String BIND_READ_JS=""+'; assert mark in s; s=s.replace(mark,planner+'\n'+prims+'\n'+mark,1)
s=s.replace('o.put("raw_text_remote",false);o.put("raw_path_remote",false);o.put("chat_effect_dispatches",0);if(extra!=null)','o.put("raw_text_remote",false);o.put("raw_path_remote",false);o.put("chat_effect_dispatches",plannerChatEffectDispatches+targetChatEffectDispatches);o.put("planner_chat_effect_dispatches",plannerChatEffectDispatches);o.put("target_chat_effect_dispatches",targetChatEffectDispatches);if(extra!=null)',1)
s=s.replace('@Override public void onBackPressed(){if(chatMode){showDashboard("Dashboard");return;}super.onBackPressed();}','@Override public void onBackPressed(){if(plannerRunning){status.setText("Planner active; Back fenced.");return;}if(chatMode){showDashboard("Dashboard");return;}super.onBackPressed();}',1)
new=PKG/'OrchestratorDashboardV94PlannerIngressActivity.java'; new.write_text(s)
cs=(PKG/'TelemetryConfigV93.java').read_text().replace('TelemetryConfigV93','TelemetryConfigV94'); (PKG/'TelemetryConfigV94.java').write_text(cs)
man=ROOT/'app/src/main/AndroidManifest.xml'; ms=man.read_text(); assert ms.count('OrchestratorDashboardV93Activity')==1; man.write_text(ms.replace('OrchestratorDashboardV93Activity','OrchestratorDashboardV94PlannerIngressActivity',1))
grad=ROOT/'app/build.gradle'; gs=grad.read_text(); assert re.search(r'versionCode\s+94\b',gs); grad.write_text(re.sub(r'versionCode\s+94\b','versionCode 95',gs,1).replace('0.89.2-stable-dashboard-telemetry-budget-repair','0.90.0-stable-dashboard-stateless-planner-recipe-only',1))
out=new.read_text(); assert out.count('.click()')==1 and out.count('worker.loadUrl(')==1; assert 'targetChatEffectDispatches++' not in out; assert all(x in out for x in ['CF_PLANNER_REQUEST v1','plannerReadJs','plannerSetDraftJs','plannerSendJs','dashboard_registry_v91.json','TURN_DOM_NOT_HYDRATED','STALE_FINISH_ROUTE_MISMATCH','OBSERVE_WAIT_STARTED']);
for bad in ['elementFromPoint','document.evaluate','XPathResult','dispatchTouchEvent','addJavascriptInterface','sendCurrentDraft']: assert bad not in out,bad
print('Generated v0.90.0 Dashboard stateless Planner recipe-only successor')
