/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SessionRouteImport } from './routes/session'
import { Route as LongitudinalRouteImport } from './routes/longitudinal'
import { Route as AthleteRouteImport } from './routes/athlete'
import { Route as IndexRouteImport } from './routes/index'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const LongitudinalRoute = LongitudinalRouteImport.update({
  id: '/longitudinal',
  path: '/longitudinal',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteRoute = AthleteRouteImport.update({
  id: '/athlete',
  path: '/athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athlete': typeof AthleteRoute
  '/longitudinal': typeof LongitudinalRoute
  '/session': typeof SessionRoute
  '/styleguide': typeof StyleguideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athlete': typeof AthleteRoute
  '/longitudinal': typeof LongitudinalRoute
  '/session': typeof SessionRoute
  '/styleguide': typeof StyleguideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athlete': typeof AthleteRoute
  '/longitudinal': typeof LongitudinalRoute
  '/session': typeof SessionRoute
  '/styleguide': typeof StyleguideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/athlete' | '/longitudinal' | '/session' | '/styleguide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/athlete' | '/longitudinal' | '/session' | '/styleguide'
  id:
    | '__root__'
    | '/'
    | '/athlete'
    | '/longitudinal'
    | '/session'
    | '/styleguide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthleteRoute: typeof AthleteRoute
  LongitudinalRoute: typeof LongitudinalRoute
  SessionRoute: typeof SessionRoute
  StyleguideRoute: typeof StyleguideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longitudinal': {
      id: '/longitudinal'
      path: '/longitudinal'
      fullPath: '/longitudinal'
      preLoaderRoute: typeof LongitudinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete': {
      id: '/athlete'
      path: '/athlete'
      fullPath: '/athlete'
      preLoaderRoute: typeof AthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthleteRoute: AthleteRoute,
  LongitudinalRoute: LongitudinalRoute,
  SessionRoute: SessionRoute,
  StyleguideRoute: StyleguideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
